### ISSUE TITLE
hwc-platform-drm-generic: Failed to close gem handle 0 -1

### ISSUE THREAD

**Issue by cmsanta** [android-ia/external-drm_hwcomposer#5]
E hwc-platform-drm-generic: Failed to close gem handle 0 -1

**Comment by txu4** [comment]
The buffer management in HWC2.0 is messy, the DrmHwcBuffer object in DrmHwcLayer, the hwc_drm_bo object in DrmHwcBuffer etc. are all passed through value, then the buffer handle, like gem_handles in hwc_drm_bo will be copied. 

The error in this log happens because the real gem object has been closed, but the handle is still hanging.
It may cause serious issue if the original gem object is closed, but another new gem object is created w/ the same handle value. It may happen w/ high probability because handle is just an int value, like 0, 1, 2.

We'd better use shared_ptr to manage these objects.

**Comment by tpalli** [comment]
Perhaps we are missing a refcount bump ... somewhere? I don't understand how we can have handles that have their objects 'already closed'. Is it because referenced gralloc buffers get destroyed and hwc_drm_bo_t is not in sync with that (which would be pretty bad ..)?

It seems nv implementation has additional recounting done in 'NvImporter::ImportBuffer', would be interesting to see how their gralloc looks like.

**Comment by txu4** [comment]
@tpalli you are right, NV platform uses the refcount to avoid this issue, and we can take this way as a quick solution. For the shared_ptr and smart pointer will be more efficient, to avoid unnecessary buffer copy.

**Comment by kalyankondapally** [comment]
Merged couple of patches we missed from @tpalli  Adding support to import buffers in Gralloc. HWC Registers and Unregisters buffers as needed, Gralloc uses this to figure out when the memory needs to be released. We where doing an extra release in HWC side which is unnecessary and removed in the original patch which introduced IAPlanner. Closing this.

**Comment by txu4** [comment]
@kalyankondapally and @tpalli  I checked the latest code, the hwc will call "perform GRALLOC_MODULE_PERFORM_DRM_IMPORT" to get the prime_fd, but it doesn't  close it when release the buffer, it may cause buffer and fd leakage. Please check. 

Btw, I have worked out a patch (based on 15199fa9380a4636f0341c242a4854f9ad99bd47) to pass/access the hwc_drm_bo through std::shared_ptr<hwc_drm_bo>, it will avoid unnecessary memory copy in function calling and solve the invalid buffer handle issue.

**Comment by kalyankondapally** [comment]
All memory tracking is done now in drm_gralloc only. HWC will register and unregister buffers. If ref count in gralloc is 0 it will close the buffer automatically.

**Comment by txu4** [comment]
@kalyankondapally thanks, I understand your point, it's better to track the memory reference count in drm_gralloc only, and use bo_reference/bo_unreference API provided by libdrm to maintain the life cycle of bo object.

Close the bug
